# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mate',
            name='text_pref',
        ),
        migrations.AddField(
            model_name='mate',
            name='group',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mate',
            name='text',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mate',
            name='whatsapp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
