# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 07:50
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_auto_20170630_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mate',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
