# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('desktop_screenshot', models.ImageField(upload_to='developer/img/desktop')),
                ('mobile_screenshot', models.ImageField(upload_to='developer/img/mobile')),
                ('brief', models.TextField()),
                ('cleverbits', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
