# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiltLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=999)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=9999, null=True)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuiltWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('alternatives', models.CharField(blank=True, max_length=500, null=True)),
                ('links', models.ManyToManyField(blank=True, to='transactions.GuiltLink')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bing_image',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'image'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='transaction',
            name='guiltwords',
            field=models.ManyToManyField(to='transactions.GuiltWord'),
        ),
    ]
