# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20170808_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
